---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: croc-hunter
  labels:
    name: croc-hunter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: gcr.io/api-project-642841493686/croc-hunter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
