---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: croc-hunter
  labels:
    name: croc-hunter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: croc-hunter
    spec:
      containers:
      - name: croc-hunter
        image: csanchez/croc-hunter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: croc-hunter
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: croc-hunter
  type: LoadBalancer
